name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.2.0
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.8.0
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        file: ./deploy/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: jarvis2f/ais-ninja:latest
    - name: Dockerhub Readme
      uses: ms-jpq/sync-dockerhub-readme@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: jarvis2f/ais-ninja
        readme: "./README.md"
        cache-from: type=gha
        cache-to: type=gha,mode=max
